# Tarea 1 a. Ejemplos capitulo 1 y 2 

## Ejemplos capitulo 1

### 1.1 Ayuda y documentación en IPython

#####  Operadores de documentación help(), ?, ??

Para accesar a información sobre alguna función se puede usar el comando __help('argumento')__ donde 'argumento' es por ejemplo la función __len__.


In [1]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



Otro método de accesar a información, que tiene sus ventajas porque no solo da información sobre funciones sino también de modulos es usando el operador __?__. Con este método el ejemplo anterior quedaría como:

In [2]:
len?

Y como mencioné también se aplica a métodos:

In [3]:
import matplotlib?

In [ ]:
import matplotlib

In [4]:
import matplotlib

Esta información se coloca, al momento de definir las funciones usando triple comilla al inicio y al final, así:

In [5]:
def cube(a):
    """Eleva al cubo un número a"""
    return a**3

Ahora usamos el operador __?__ para acceder a la descripción que hemos escrito.

In [6]:
cube?

Otro operador es __??__ que permite acceder al código, pero solo si éste esta escrito en python, si esta implementado en C o C++, se regresa el mismo valor que con el operador __?__. A continuación un ejemplo del uso de __??__ con la función que acabamos de definir:

In [7]:
cube??

Y ahora lo que se mencionó cuando __??__ no funciona:

In [8]:
len??

In [9]:
len?

Note que len?? y len? devuelven los mismos valores.


#####  Autocompletado usando TAB

Para autocompletar sentencias se emplea la tecla TAB, y eso devuelve todas las posibles opciones de autocompletado.

###  1.2 Atajos de teclado en la consola de IPython

Se tienen varios atajos de teclado en la consola de IPython, se deben practicar para familiarizarse con ellos. Los que me parecen más importantes son:

Ctrl-l para limpiar la consola

Ctrl-c para interrumpir un proceso

Ctrl-d para salir de IPhyton

###  1.3 Los _magic commands_ de IPython

Los _magic commands_ son añadidos de IPython sobre el lenguaje Python, deben ir precedidos por el caracter __%__.

In [10]:
>>> def donothing(x):
...     return x

In [11]:
donothing(10)

10

Se tiene el _magic command_ __%paste__ pero en el notebook no fue necesario usarlo y en la consola de IPython no supe cómo usarlo.

Primero escribí: %paste, luego pegue y no funcionó.

El comando __%cpaste__ sirve para pegar código formateado y ejecutarlo dentro de la consola de IPython sin que el formato afecte la ejecución:

Otro comando es __%run__ , sirve para ejecutar scripts de python .py dentro de la consola de IPython y también da acceso a sus funciones, tal cual como si se ubiera escrito en la consola.

In [12]:
#Este es el programa myscript.py
def square(x):
    """square a number"""
    return x**2

for N in range(1,4):
    print(N,"squared is",square(N))

1 squared is 1
2 squared is 4
3 squared is 9


In [13]:
%run myscript.py

1 squared is 1
2 squared is 4
3 squared is 9


In [14]:
square(25)

625

El comando __%timeit__ devuelve el tiempo de ejecución de una línea de código haciendo estadística tras ejecutar varias veces la línea.

In [15]:
%timeit L=[n**2 for n in range(10000)]

2.97 ms ± 369 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Usando __%%timeit__ se pueden tomar varias lineas:

In [16]:
%%timeit
L=[]
for n in range(1000):
    L.append(n ** 2)

325 µs ± 4.69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


####  Ayuda en _magic functions_ ?, %magic, y %lsmagic

In [17]:
%timeit?

Información sobre la función __%timeit__. En general se puede accesar a la información sobre cualquier _magic function_ usando __?__ en la forma usual.

In [18]:
%magic

Información sobre las _magic functions_

In [19]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

Lista de las _magic functions_ disponibles

###  1.4 Input and Output History

__In[]__ y __Out[]__ son más que decoración de IPython, ya que van almacenando respectivamente todas las entradas y todas las salidas, el número corresponde al indice del elemento.

In [20]:
print(In)

['', 'help(len)', "get_ipython().run_line_magic('pinfo', 'len')", "get_ipython().set_next_input('import matplotlib');get_ipython().run_line_magic('pinfo', 'matplotlib')", 'import matplotlib', 'def cube(a):\n    """Eleva al cubo un número a"""\n    return a**3', "get_ipython().run_line_magic('pinfo', 'cube')", "get_ipython().run_line_magic('pinfo2', 'cube')", "get_ipython().run_line_magic('pinfo2', 'len')", "get_ipython().run_line_magic('pinfo', 'len')", 'def donothing(x):\n    return x', 'donothing(10)', '#Este es el programa myscript.py\ndef square(x):\n    """square a number"""\n    return x**2\n\nfor N in range(1,4):\n    print(N,"squared is",square(N))', "get_ipython().run_line_magic('run', 'myscript.py')", 'square(25)', "get_ipython().run_line_magic('timeit', 'L=[n**2 for n in range(10000)]')", "get_ipython().run_cell_magic('timeit', '', 'L=[]\\nfor n in range(1000):\\n    L.append(n ** 2)\\n')", "get_ipython().run_line_magic('pinfo', '%timeit')", "get_ipython().run_line_magic('ma

In[] es una lista, donde el número corresponde con el índice del elemento de la lista.

In [21]:
Out

{11: 10,
 14: 625,
 19: Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%

Out[] es un diccionario que mapea los números de la entrada (In[]) con sus salidas (si es que las hay). No todas las operaciones tienen salidas, por ejemplo __import__ y __print__.

Los objetos In[] y Out[] pueden ser bastante utiles a la hora de reducir el coste computacional reciclando resultados de operaciones previamente calculados.

#### Atajos  con guión bajo y salidas previas.

Para accesar a la salida anterior se usa el atajo '\_' (guión bajo):

In [22]:
2+3

5

In [23]:
print(_)

5


En IPython además, se puede usar doble o triple guión bajo para acceder a la penultima y antepenultima salidas respectivamente.

####  Suprimiendo la salida

Si deseamos suprimir la salida de una línea se añade un ';' (punto y coma) al final de la línea.

In [24]:
3+5;

In [25]:
40 in Out

False

####  _Magic Commands_ relacionados

In [26]:
%history

help(len)
len?
import matplotlib?
import matplotlib
def cube(a):
    """Eleva al cubo un número a"""
    return a**3
cube?
cube??
len??
len?
>>> def donothing(x):
...     return x
donothing(10)
#Este es el programa myscript.py
def square(x):
    """square a number"""
    return x**2

for N in range(1,4):
    print(N,"squared is",square(N))
%run myscript.py
square(25)
%timeit L=[n**2 for n in range(10000)]
%%timeit
L=[]
for n in range(1000):
    L.append(n ** 2)
%timeit?
%magic
%lsmagic
print(In)
Out
2+3
print(_)
3+5;
40 in Out
%history


Se usa para ver todas las entradas previas. Para ver las primeras 6:

In [27]:
%history -n 1-6

   1: help(len)
   2: len?
   3: import matplotlib?
   4: import matplotlib
   5:
def cube(a):
    """Eleva al cubo un número a"""
    return a**3
   6: cube?


%rerun se usa para volver a ejecutar alguna porción de código.

%save almacena en un archivo alguna porción de código.

Para más información usar __?__.

### 1.5  IPython y los comandos _shell_

(Solo en IPython) Para ejecutar comandos del _shell_ dentro de la consola de IPython se coloca el signo __!__ antes del comando.


In [28]:
!ls

README.md  Semana1  Tarea1.ipynb  myscript.py  prueba1.txt


In [29]:
!pwd

/home/rodolfo/cursos/analisis-de-datos/da2019-R-Ernesto


In [30]:
!echo "printing from the shell"

printing from the shell


También se pueden combinar comandos _shell_ y de _python_

In [31]:
contents = !ls

In [32]:
contents

['README.md', 'Semana1', 'Tarea1.ipynb', 'myscript.py', 'prueba1.txt']

In [33]:
directory = !pwd

In [34]:
pwd

'/home/rodolfo/cursos/analisis-de-datos/da2019-R-Ernesto'

In [35]:
message="hello from python"

In [36]:
!echo {message}

hello from python


###  Los _magic commands_ en _shell_

Para cambiar de directorio desde la consola de ipython no se puede usar !cd, en vez de eso se utiliza %cd

In [37]:
%cd ..

/home/rodolfo/cursos/analisis-de-datos


In [38]:
%cd /home/rodolfo/cursos/analisis-de-datos/da2019-R-Ernesto/

/home/rodolfo/cursos/analisis-de-datos/da2019-R-Ernesto


¿Esto podría servir para accesar a archivos que no se hallen en el directorio de trabajo actual?

también se puede usar cd sin el signo %

In [39]:
cd ..

/home/rodolfo/cursos/analisis-de-datos


In [40]:
cd  da2019-R-Ernesto/

/home/rodolfo/cursos/analisis-de-datos/da2019-R-Ernesto


Otras funciones _shell-magicas_:

    -%cat
    -%cp
    -%env
    -%ls
    -%man
    -%mkdir
    -%more
    -%mv
    -%pwd
    -%rm
    -%rmdir

Las anteriores se pueden usar también sin el signo % si la funcion _automagic_ esta activa.

¿Cómo se activa la función automagic? es solo %automagic?

###  1.6 Errores y Depuración

La mayor parte de la veces que un script python falla, se levanta una bandera _Exception_, cuando esto ocurre se despliega información en la consola de la causa de la exepción, con la _magic function_ __%xmode__ (corto para _exception mode_) se puede cambiar la forma en la que se despliega dicha información habiendo 3 modos:

    -Plain 
    -Verbose
    -Context

In [41]:
def div(a,b):
    return a/b
def func(x):
    a=x
    b=x-1
    return div(a,b)

In [42]:
%xmode Context

Exception reporting mode: Context


In [43]:
func(1)

ZeroDivisionError: division by zero

Información desplegada por defecto, el modo es _Context_.

In [44]:
%xmode Plain

Exception reporting mode: Plain


In [45]:
func(1)

ZeroDivisionError: division by zero

Note que hay menos información que en el modo por defecto.



In [46]:
%xmode Verbose

Exception reporting mode: Verbose


In [47]:
func(1)

ZeroDivisionError: division by zero

El modo verbose es el que devuelve más información.

#### pdb (python debugger)

Python debbuger es la herramienta de depuración estándar de python, en ipython se han implementado mejoras y la herramienta adopta el nombre de __ipdb__. Para activar la interfaz de depuración se emplea el _magic command_ __%debug__.

In [48]:
%debug

> <ipython-input-41-664ece033c43>(2)div()
      1 def div(a,b):
----> 2     return a/b
      3 def func(x):
      4     a=x
      5     b=x-1

ipdb> 
ipdb> 
ipdb> q


__ipdb__ nos permite explorar los valores de las variablese incluso ejecutar comandos de python. Para salir escribir __quit__, para imprimir las variables __print__ 'nombre de la variable'.

In [49]:
%debug

> <ipython-input-41-664ece033c43>(2)div()
      1 def div(a,b):
----> 2     return a/b
      3 def func(x):
      4     a=x
      5     b=x-1

ipdb> q


Podemos movernos en la pila instrucciones arriba (usando __up__) y abajo (usando __down__) y explorar los valores de las variables.

Si queremos que el depurador (__pdb__) se 'lance' en automático cuando ocurra una exceción usamos __%pdb on__.

In [50]:
%xmode Plain
%pdb on
func(1)

Exception reporting mode: Plain
Automatic pdb calling has been turned ON


ZeroDivisionError: division by zero

> <ipython-input-41-664ece033c43>(2)div()
      1 def div(a,b):
----> 2     return a/b
      3 def func(x):
      4     a=x
      5     b=x-1

ipdb> q


Para ejecutar un script línea por línea usamos __%run -d__ y usando la instrucción __next__ se avanza línea a línea.

__Command__   &  __Description__

__list__:          Show the current location in the file

__h(elp)__:        Show a list of commands, or find help on a specific command

__q(uit)__:        Quit the debugger and the program

__c(ontinue)__:    Quit the debugger, continue in the program

__n(ext)__:        Go to the next step of the program

__\< enter \>__:       Repeat the previous command
    
__p(rint)__:       Print variables

__s(tep)__:        Step into a subroutine

__r(eturn)__:      Return out of a subroutine

###  1.7 Perfilación y temporización de código

Cuando se esta trabajando en un programa no vale la pena preocuparse por la optimización sino porque funcione, por otra parte una vez que ya esta funcionando valdría la pena optimizarlo un poco. En ipython existen varias herramientas para optimizar nuestro código:
    
    -%time
        
        -tiempo de ejecución de una instrucción
        
    -%timeit
        
        -tiempo de ejecución de una instrucción con algo de estadística para mayor precisión
        
    -%prun
        
        -ejecutar el código con el _profiler_
        
    -%lprun
    
        -ejecutar el código instrucción por línea con el _profiler_
    
    -%memit
    
        -medir el uso de memoria de una sola instrucción
        
    -%mprun
    
        -run code with the line-by-line memory profiler
        
Las últimas cuatro instruciones no vienen por defecto en ipython, se necesitan descargar extensiones.      
        

Repetir una operación para hallar su tiempo de ejecución promedio a veces no es la mejor opción, en esos casos es mejor usar %time en vez de %timeit. Por ejemplo si queremos ordenar una lista, si lo hacemos varias veces sesgamos el resultado porque es más sencillo ordenar una lista previamente ordenada. ¿Y eso por qué?

###  1.8 Más recursos de ipython

Bibliografías recomendadas para aprender más.

##  Ejemplos capítulo 2

### Introducción a NumPy

_Toda la información es fundamentalmente arreglos de números_. No importa el tipo de información, lo primero que hay que hacer al analizarla es convertirla en arreglos de números.

### NumPy

NumPy (Numerical Python) provee una variedad de herramientas para manipular y almacenar volumenes densos de información.

In [51]:
import numpy
numpy.__version__sion__

AttributeError: module 'numpy' has no attribute '__version__sion__'

> <ipython-input-51-6b8fd02e4f9e>(2)<module>()
      1 import numpy
----> 2 numpy.__version__sion__

ipdb> 


En DA se suele abreviar numpy como np al importarlo:

In [52]:
import numpy as np

###  2.1 Entendiendo los tipos de datos en python

Python esta implementado en lenguaje C, es decir que cada objeto en python es una estructura escrita en C que contiene no solo su valor, sino otra información además.

Los datos en python no son solo datos en la memoria, eso son en C, acá son varias locaciones en la memoria con distintos parámetros sobre el dato de python.

Los arreglos de tipo fijo de NumPy son más eficientes para almacenar y manipular información porque no tienen ese 'problema' de los objetos de python, se parece más a lo que era C.

Existen varios módulos de arreglos de tipo fijo, uno de ellos es __array__.

In [53]:
import array
L=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Dónde 'i' es la definición del tipo de objetos del arreglo, en este caso enteros (_int_).

Usando np.array podemos crear arreglos desde las listas de python.

In [54]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

(Aqui podriamos suprimir la salida si no la necesitamos)

In [55]:
np.array([1,4,2,5,3]);

Entonces a diferencia de las listas de python los arreglos de Numpy estan limitados a objetos de un mismo tipo y si los objetos no coinciden numpy los 'convierte' (_casting_) al tipo de objeto mayor (_upcasting_).

In [56]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

Si deseamos darle un tipo de forma explícita empleamos __dtype__:

In [57]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Otra diferencia es que los arreglos en __np__ puedens ser explícitamente multidimensionales a diferencia de las listas de python.

In [58]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Las listas interiores son tratadas como renglones en una matris 2D.

#####  Creando arreglos usando rutinas de np

In [59]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Arreglo de longitud 10 rellenado con ceros.

In [60]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Arreglo de 3*5 relleno con unos flotantes. Pero se puede rellenar con lo que quiera uno:

In [61]:
np.full((3,5),5.789)

array([[5.789, 5.789, 5.789, 5.789, 5.789],
       [5.789, 5.789, 5.789, 5.789, 5.789],
       [5.789, 5.789, 5.789, 5.789, 5.789]])

Un arreglo de 0 a 20 de dos en dos.

In [62]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Un arreglo de 0 a 1 con 5 elementos igualmentes espaciados entre ellos.

In [63]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Un arreglo con valores aleatorios normalmente distribuidos con media 0 y stdev 1.

In [64]:
np.random.normal(0,1,(3,3))

array([[-1.21389507,  1.43860059, -0.31903691],
       [-0.44080849, -0.18777731,  1.0587441 ],
       [-0.87879623, -0.14091713, -0.70419749]])

Arreglo con números aleatorios en el intervalo de 0 a 10.

In [65]:
np.random.randint(0,10,(3,3))

array([[5, 0, 7],
       [4, 3, 1],
       [3, 9, 9]])

Una matriz identidad de 3x3

In [66]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Un arreglo vacio de 4 elementos. Los valores corresponden a datos en la memoria.

In [67]:
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])

#####  Tipos de Datos en np

https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html

### 2.2 The basics of np arrays

-Atributos de arreglos

-Indexación de arreglos

-Particion de arreglos

-Reformando arreglos

-Uniendo y separando arreglos

In [68]:
np.random.seed(0) #para que los arreglos sean iguales cada vez que se ejecuta

x1 = np.random.randint(10, size=6) #Arreglo uno-dimensional
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [69]:
#número de dimensiones
x3.ndim

3

In [70]:
x2.ndim

2

In [71]:
x1.ndim

1

In [72]:
#forma
x2.shape

(3, 4)

In [73]:
x1.shape

(6,)

In [74]:
x3.shape

(3, 4, 5)

In [75]:
#tamaño
x1.size

6

In [76]:
x3.size

60

In [77]:
x2.size

12

In [78]:
#tipo
x1.dtype

dtype('int64')

In [79]:
x2.dtype

dtype('int64')

In [80]:
x3.dtype

dtype('int64')

In [81]:
#tamaño en bytes de cada elemento del arreglo
x1.itemsize

8

In [82]:
x2.itemsize

8

In [83]:
x3.itemsize

8

In [84]:
#tamaño en bytes del arrego
x1.nbytes

48

In [85]:
x2.nbytes

96

In [86]:
x3.nbytes

480

In [87]:
# nbytes of the array= itemsize*size of the array
x3.itemsize * x3.size

480

#####  Array indexing: accesando a elementos particulares

In [88]:
x1

array([5, 0, 3, 3, 7, 9])

In [91]:
x1[0]

5

In [92]:
x1[5]

9

In [93]:
x1[-1]

9

In [94]:
x1[-2]

7

In [95]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [96]:
x2[0,0]

3

In [97]:
x2[2,0]

1

In [98]:
x2[2,-1]

7

In [99]:
x2[0,0]=12

In [100]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])