# Ejemplos capitulo 2 

### Introducción a NumPy

_Toda la información es fundamentalmente arreglos de números_. No importa el tipo de información, lo primero que hay que hacer al analizarla es convertirla en arreglos de números.

### NumPy

NumPy (Numerical Python) provee una variedad de herramientas para manipular y almacenar volumenes densos de información.

In [1]:
import numpy
numpy.__version__

'1.16.4'

En DA se suele abreviar numpy como np al importarlo:

In [2]:
import numpy as np

###  2.1 Entendiendo los tipos de datos en python

Python esta implementado en lenguaje C, es decir que cada objeto en python es una estructura escrita en C que contiene no solo su valor, sino otra información además.

Los datos en python no son solo datos en la memoria, eso son en C, acá son varias locaciones en la memoria con distintos parámetros sobre el dato de python.

Los arreglos de tipo fijo de NumPy son más eficientes para almacenar y manipular información porque no tienen ese 'problema' de los objetos de python, se parece más a lo que era C.

Existen varios módulos de arreglos de tipo fijo, uno de ellos es __array__.

In [3]:
import array
L=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Dónde 'i' es la definición del tipo de objetos del arreglo, en este caso enteros (_int_).

Usando np.array podemos crear arreglos desde las listas de python.

In [4]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

(Aqui podriamos suprimir la salida si no la necesitamos)

In [5]:
np.array([1,4,2,5,3]);

Entonces a diferencia de las listas de python los arreglos de Numpy estan limitados a objetos de un mismo tipo y si los objetos no coinciden numpy los 'convierte' (_casting_) al tipo de objeto mayor (_upcasting_).

In [6]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

Si deseamos darle un tipo de forma explícita empleamos __dtype__:

In [7]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Otra diferencia es que los arreglos en __np__ puedens ser explícitamente multidimensionales a diferencia de las listas de python.

In [8]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Las listas interiores son tratadas como renglones en una matris 2D.

#####  Creando arreglos usando rutinas de np

In [9]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Arreglo de longitud 10 rellenado con ceros.

In [10]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Arreglo de 3*5 relleno con unos flotantes. Pero se puede rellenar con lo que quiera uno:

In [11]:
np.full((3,5),5.789)

array([[5.789, 5.789, 5.789, 5.789, 5.789],
       [5.789, 5.789, 5.789, 5.789, 5.789],
       [5.789, 5.789, 5.789, 5.789, 5.789]])

Un arreglo de 0 a 20 de dos en dos.

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Un arreglo de 0 a 1 con 5 elementos igualmentes espaciados entre ellos.

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Un arreglo con valores aleatorios normalmente distribuidos con media 0 y stdev 1.

In [14]:
np.random.normal(0,1,(3,3))

array([[ 0.76839262, -2.44130597, -1.19793332],
       [ 0.79406917,  0.32672523,  0.25842066],
       [ 0.91107231, -0.93792123, -0.06878667]])

Arreglo con números aleatorios en el intervalo de 0 a 10.

In [15]:
np.random.randint(0,10,(3,3))

array([[8, 9, 9],
       [2, 8, 8],
       [0, 0, 1]])

Una matriz identidad de 3x3

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Un arreglo vacio de 4 elementos. Los valores corresponden a datos en la memoria.

In [17]:
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])

#####  Tipos de Datos en np

https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html

### 2.2 The basics of np arrays

-Atributos de arreglos

-Indexación de arreglos

-Particion de arreglos

-Reformando arreglos

-Uniendo y separando arreglos

In [18]:
np.random.seed(0) #para que los arreglos sean iguales cada vez que se ejecuta

x1 = np.random.randint(10, size=6) #Arreglo uno-dimensional
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [19]:
#número de dimensiones
x3.ndim

3

In [20]:
x2.ndim

2

In [21]:
x1.ndim

1

In [22]:
#forma
x2.shape

(3, 4)

In [23]:
x1.shape

(6,)

In [24]:
x3.shape

(3, 4, 5)

In [25]:
#tamaño
x1.size

6

In [26]:
x3.size

60

In [27]:
x2.size

12

In [28]:
#tipo
x1.dtype

dtype('int64')

In [29]:
x2.dtype

dtype('int64')

In [30]:
x3.dtype

dtype('int64')

In [31]:
#tamaño en bytes de cada elemento del arreglo
x1.itemsize

8

In [32]:
x2.itemsize

8

In [33]:
x3.itemsize

8

In [34]:
#tamaño en bytes del arrego
x1.nbytes

48

In [35]:
x2.nbytes

96

In [36]:
x3.nbytes

480

In [37]:
# nbytes of the array= itemsize*size of the array
x3.itemsize * x3.size

480

#####  Array indexing: accesando a elementos particulares

In [38]:
x1

array([5, 0, 3, 3, 7, 9])

In [39]:
x1[0]

5

In [40]:
x1[5]

9

In [41]:
x1[-1]

9

In [42]:
x1[-2]

7

In [43]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [44]:
x2[0,0]

3

In [45]:
x2[2,0]

1

In [46]:
x2[2,-1]

7

In [47]:
x2[0,0]=12

In [48]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [49]:
x1

array([5, 0, 3, 3, 7, 9])

In [50]:
x1[0]=3.14159

In [51]:
x1

array([3, 0, 3, 3, 7, 9])

Debido a que x1 es de tipo int el valor flotante que tratamos de asignar al elemento se trunca.

####  Arrays slicing (particionado)

In [52]:
x = np.arange(10)

In [53]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x[:5]

array([0, 1, 2, 3, 4])

In [55]:
x[5:]

array([5, 6, 7, 8, 9])

In [56]:
x[4:7]

array([4, 5, 6])

In [57]:
x[::2]

array([0, 2, 4, 6, 8])

In [58]:
x[1::2]

array([1, 3, 5, 7, 9])

In [59]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [60]:
x[5::-2]

array([5, 3, 1])

In [61]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [62]:
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [63]:
x2[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [64]:
x2[::-1,::-1] #transpuesta

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accesando a renglones y columnas

In [65]:
x2[:,0]

array([12,  7,  1])

In [66]:
x2[0,:]

array([12,  5,  2,  4])

Importante usar ':'

In [67]:
x2[0]

array([12,  5,  2,  4])

In [68]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [69]:
x2_sub = x2[:2,:2]
x2_sub

array([[12,  5],
       [ 7,  6]])

In [70]:
x2_sub[0,0]=99

In [71]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Modificar el arreglo sub, modifica al arreglo original, sub no es una copia!

_This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer._

#####  Creando copias de arreglos

In [72]:
x2_sub_copy = x2[:2,:2].copy()

In [73]:
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [74]:
x2_sub_copy[0,0]=101

In [75]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

####  Reformando Arreglos

In [76]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El tamaño del arreglo original debe coincidir con el arreglo final.

In [77]:
x=np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [78]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [79]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [80]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

_We will see this type of transformation often throughout the remainder of the book._

#### Union y división de arreglos

In [82]:
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.array([99,99,99])
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [83]:
grid = np.array([[1,2,3],[4,5,6]])

In [85]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [86]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [87]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [88]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])